name: Ubuntu CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - devel

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - 
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    submodules: 'recursive'
            -
                name: Setup conan 2.0
                run: |
                  sudo apt-get update
                  sudo apt-get install python3-pip
                  pip3 install conan
                  conan profile detect
            - 
                name: Compile code and run tests
                run: |
                    conan install . --build=missing
                    cmake --preset conan-release
                    cmake --build --preset conan-release
                    cd build/Release
                    ctest