name: Ubuntu CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - devel

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - 
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    submodules: 'recursive'
            - 
                name: Compile code
                run: |
                    mkdir -p build
                    cd build
                    cmake ..
                    make -
            - 
                name: Run tests
                run: ctest --output-on-failure